### ISSUE TITLE
IDE Error

### ISSUE THREAD

**Issue by PumpkinSeed** [carbonblack/intellij-rpmspec#2]
I got an error on the latest version of this plugin on version 0.9.7 
Goland 2019.1.3 Build 191.7479.32

```
java.nio.file.NoSuchFileException: /usr/local/Cellar/rpm/4.14.2.1/lib/rpm/macros.d
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
	at java.nio.file.Files.walk(Files.java:3574)
	at java.nio.file.Files.walk(Files.java:3625)
	at com.carbonblack.intellij.rpmmacro.RpmMacroUtil$macroPathFiles$2.invoke(RpmMacroUtil.kt:66)
	at com.carbonblack.intellij.rpmmacro.RpmMacroUtil$macroPathFiles$2.invoke(RpmMacroUtil.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.carbonblack.intellij.rpmmacro.RpmMacroUtil.getMacroPathFiles(RpmMacroUtil.kt)
	at com.carbonblack.intellij.rpmmacro.RpmMacroFileType.isMyFileType(RpmMacroFileType.kt:16)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getByFile(FileTypeManagerImpl.java:568)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:540)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:327)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.createFileViewProvider(FileManagerImpl.java:258)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:205)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:365)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:160)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.getFiles(PsiDirectoryImpl.java:146)
	at com.goide.sdk.GoPackageUtil.getAllPackagesInDirectoryInner(GoPackageUtil.java:106)
	at com.goide.sdk.GoPackageUtil.getAllPackagesInDirectory(GoPackageUtil.java:88)
	at com.goide.psi.impl.GoPackage.in(GoPackage.java:108)
	at com.goide.psi.impl.imports.DefaultGoImportResolver.lambda$findPackagesInContexts$4(DefaultGoImportResolver.java:122)
	at one.util.streamex.AbstractStreamEx.lambda$flatCollection$16(AbstractStreamEx.java:556)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:344)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1154)
	at com.goide.psi.impl.imports.DefaultGoImportResolver.findPackagesInContexts(DefaultGoImportResolver.java:123)
	at com.goide.psi.impl.imports.DefaultGoImportResolver.innerResolve(DefaultGoImportResolver.java:67)
	at com.goide.psi.impl.imports.DefaultGoImportResolver.lambda$null$0(DefaultGoImportResolver.java:50)
	at com.intellij.util.containers.ConcurrentFactoryMap$3.create(ConcurrentFactoryMap.java:192)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:45)
	at com.goide.psi.impl.imports.DefaultGoImportResolver.resolve(DefaultGoImportResolver.java:55)
	at com.goide.sdk.GoPackageUtil.findByImportPath(GoPackageUtil.java:168)
	at com.goide.execution.testing.GoTestRunConfiguration.checkConfiguration(GoTestRunConfiguration.java:133)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.checkSettings(RunnerAndConfigurationSettingsImpl.kt:310)
	at com.intellij.execution.RunnerAndConfigurationSettings.checkSettings(RunnerAndConfigurationSettings.java:116)
	at com.intellij.execution.impl.TimedIconCache.calcIcon(TimedIconCache.kt:71)
	at com.intellij.execution.impl.TimedIconCache.access$calcIcon(TimedIconCache.kt:18)
	at com.intellij.execution.impl.TimedIconCache$get$$inlined$write$lambda$1.fun(TimedIconCache.kt:50)
	at com.intellij.execution.impl.TimedIconCache$get$$inlined$write$lambda$1.fun(TimedIconCache.kt:18)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:280)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:165)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:121)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:89)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:164)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tlusk** [comment]
@PumpkinSeed I think I see what might be causing it, I'll take a look shortly and try to get a fix out.

**Comment by tlusk** [comment]
@PumpkinSeed sorry it took me a little longer to get around to this than I expected.  The problem should be resolved in the following commit: https://github.com/carbonblack/intellij-rpmspec/commit/b8ebe9130fb12dd03ec454c28b8565cd46da3bde

I've submitted a new version 0.9.8 and it should be approved and show up for you within 48 hours.
